### ISSUE TITLE
Parse ENUM constants

### ISSUE THREAD

**Issue by dominicbarnes** [BrunnerLivio/pokemongo-game-master#18]
iirc, there is a section of the `.proto` dedicated to lists of constants, such as:

```
POKEMON_TYPE_NORMAL: 1
```

Downstream, it's impossible to match the numbers in `typeEffective.attackScalar` with the corresponding type without the original ID numbers.

It would be great to include those enums alongside `itemTemplates`.

**Comment by celandro** [comment]
This is not part of the json file. You probably want https://github.com/Furtif/POGOProtos/tree/master/src/POGOProtos/Enums
