### ISSUE TITLE
attackScalar value array order?

### ISSUE THREAD

**Issue by truimagz** [BrunnerLivio/pokemongo-game-master#2]
Anyone know what the array order is for the attackScalar type values?

I see just an array of values, don't know where to ref the key though.

**Comment by BrunnerLivio** [comment]
Maybe post this question on [/r/pokemongodev](https://www.reddit.com/r/pokemongodev/)? 

If you find the solution, it would be awesome if you could post it here also!

**Comment by truimagz** [comment]
I've figured it out, its the default order pogo uses... 

Thank you for the response, I've built this with your game master file pogonium.com

If anyone needs help making something let me know.

**Comment by BrunnerLivio** [comment]
@truimagz 
Cool! 

Is pogonium open source? I'm thinking about linking projects which depend on this repository. For future developer as a starting reference.

If it is open source, can I link it in the readme?

**Comment by truimagz** [comment]
I don't have a git for it, but Id be more than happy to set one up. Ill do it today and post back later.

Thanks for this repo!

**Comment by truimagz** [comment]
Here we go

https://github.com/truimagz/pogonium

Should have plenty of helpful formulas and graphic assets for people to ref.... or even expand on the app.

Thanks again
