### ISSUE TITLE
0.83.3 - All Gen 3 Pokemon have quick move Splash and charged move Struggle

### ISSUE THREAD

**Issue by Hedva** [BrunnerLivio/pokemongo-game-master#27]
All Gen 3 Pokemon have quick move Splash and charged move Struggle
Is this a compile error of is it just the data provided by the game?

https://github.com/BrunnerLivio/pokemongo-game-master/tree/master/versions/0.83.3

Edit: charged move is struggle for every gen 3 pokemon

**Comment by celandro** [comment]
This is what is provided by the game
