### ISSUE TITLE
Legacy Moves

### ISSUE THREAD

**Issue by truimagz** [BrunnerLivio/pokemongo-game-master#3]
Any chance of getting the legacy moves added?

One can dream right. Thanks anyway, this repo rocks either way.

**Comment by BrunnerLivio** [comment]
They are added as far as I know?

Pokemon Templates have the attributes `quickMoves` and `cinematicMoves`.

```
"quickMoves": [
"VINE_WHIP_FAST",
"TACKLE_FAST"
],
"cinematicMoves": [
"SLUDGE_BOMB",
"SEED_BOMB",
"POWER_WHIP"
]
```

More information about e.g. SLUDGE_BOMB can be used using the MOVE template

```
{
"templateId": "V0090_MOVE_SLUDGE_BOMB",
"moveSettings": {
"movementId": "SLUDGE_BOMB",
"animationId": 5,
"pokemonType": "POKEMON_TYPE_POISON",
"power": 80,
"accuracyChance": 1,
"criticalChance": 0.05,
"staminaLossScalar": 0.09,
"trainerLevelMin": 1,
"trainerLevelMax": 100,
"vfxName": "sludge_bomb",
"durationMs": 2300,
"damageWindowStartMs": 1100,
"damageWindowEndMs": 2100,
"energyDelta": -50
}

```
or am I missing your point?

**Comment by truimagz** [comment]
For insurance look at dragonite. His move lists dont contain legacy moves like Dragon claw for instance.

Nor do i see that move in the data anywhere.

This is an excellent json and i have no problem making the connections but there doesn't seem to be any legacy moves.

Thanks

**Comment by truimagz** [comment]
Don't break your back, but if it's possible im sure this repo would get much attention.

The silph road has one, but i think they manually did it. And aren't sharing.

**Comment by BrunnerLivio** [comment]
I get your point @truimagz. Your thoughts on this @celandro ?

Maybe we added a faulty GAME_MASTER protobuf file? 

Either way, we won't manually add any data to the .json file. This repo is just for the raw GAME_MASTER data. But I'm currently writing on a project, which is exactly for manually editing stuff, called  [pokemongo-data-normalizer](https://github.com/BrunnerLivio/pokemongo-data-normalizer) "transforms the data from the Pokemon GO master files to a better readable & processable JSON file.". So if we want to add for instance Dragon Claw manually, we should do it in this repo.

**Comment by celandro** [comment]
The game master file does NOT have legacy movesets. The way to create it is to load older game master files and merge the data together in your app.

Here is how I do it to accurately portray both legacy moves and legacy movesets:
https://github.com/celandro/pokebattler-fight/blob/master/src/main/java/com/pokebattler/fight/data/CombinedPokemonRepository.java

**Comment by BrunnerLivio** [comment]
@celandro 
Oh okay, did not know that. So should we add legacy moves to this repository? 

The disadvantage is; we loose the ability of having raw game_master data, because we would have to alter every game_master, by merging the older version together. 

Maybe have for each version a GAME_MASTER_RAW.json and a GAME_MASTER_WITH_LEGACY_MOVES.json or so? Or is this idiotic?

**Comment by celandro** [comment]
No way. If people want legacy moves, they need to merge jsons themselves.

I think we should just have directories for historical files. Either directories or protos. The big issue is I do not have a historical proto from before the first moveset changes, i only have an old json file.

You can see the older files here:
https://github.com/celandro/pokebattler-fight/commits/master/src/main/resources/com/pokebattler/fight/data/pokemongo.json

**Comment by BrunnerLivio** [comment]
@celandro yes this totally makes sense. Thanks !

Seems like a task for my pokemon-data-normalizer repo. So @truimagz, here you go. You can add it by yourself or use my repo [pokemon-data-normalizer](https://github.com/BrunnerLivio/pokemongo-data-normalizer), as soon I've implemented it there.

**Comment by truimagz** [comment]
@celandro do you have a merged json on hand?

Not sure how much editing your doing in the merge, is that feb16 file accurate move time and damage wise? If so i could sure use it if you don't have a merge.

Of course at the end of the day i can look through and accomplish this based on your direction and information provided. 

Have other features I'm working on would rather put off this build process to later.

**Comment by celandro** [comment]
The feb16 file is accurate per feb 16 so has the old damage/speeds. It is useful for pulling in the moves.  Movesets is a bit more tricky due to there being 2 different moveset changes. Im not doing it correctly myself as I don't have a clean super legacy json or proto file..

If you don't want to do it yourself, you can just save a copy of https://fight.pokebattler.com/pokemon/

My main point is that the main files should be unedited. Any sort of modification should be done preferably in another project or at least in another directory.

**Comment by truimagz** [comment]
Thanks for all the help.

Here's what I'm building btw http://pogonium.com
