### ISSUE TITLE
Add small script for adding new versions

### ISSUE THREAD

**Issue by BrunnerLivio** [BrunnerLivio/pokemongo-game-master#30]
The instructions to add a new or older version is quite complicated. It would be much nicer if we have a script, which can be parameterized to do your work.

Example for adding latest version
```bash
$ ./pokemongo-game-master/bin/add-version.sh -f ./newversion.protobuf -v "0.83.2-1" --latest
```

Example for adding specific version
```bash
$ ./pokemongo-game-master/bin/add-version.sh -f ./newversion.protobuf -v "0.83.2-1"
```

It should first generate the JSON file, then create the needed folders ("latest" and "0.83.2-1" folder), copy the files to the correct folder and then update latest-version.txt

**Comment by celandro** [comment]
Script should only have to copy the file into the latest folder, run the
docker convert, then copy the latest folder to a new folder
