### ISSUE TITLE
past game_master versions

### ISSUE THREAD

**Issue by dominicbarnes** [BrunnerLivio/pokemongo-game-master#34]
I'm using this repository in a tool of my own to extract metadata about the game. My next goal is to get legacy moves, which to me it seems like the best course of action is to incrementally build via all known `GAME_MASTER` files. This repo currently only goes back to Feb 2017, which is pretty extensive, but is still missing 6-7 months of other versions.

If anyone knows of a way to get at the older versions, I'm more than happy to do the manual work required to contribute them here. However, I'm afraid that getting the older versions after-the-fact is not possible, is that in fact the case? (or is there some other archive of files that someone else has been maintaining longer than this one)

**Comment by rmkane** [comment]
I was considering doing something similar but have yet to compile all ther previous versions like you suggest. Version 1.0 and on can be found here:

* July 16, 2016 — [Decoded GAME_MASTER protobuf file v0.1 - all Pokemon, move, item stats](https://reddit.com/r/pokemongodev/comments/4t59t1)
* September 11, 2016 — [Pokemon GO 0.37.0 GAME_MASTER](https://gist.github.com/apavlinovic/708512ba1f4e3ce8f823d2c95912dc12)

I just used the following query in Google:

> https://google.com/search?q="GAME_MASTER"&tbs=cdr%3A1%2Ccd_min%3A7%2F2016%2Ccd_max%3A9%2F2016

**Note:** The `tbs` query param is just an encoded date range for the Google search tools:

> `cdr:1,cd_min:7/2016,cd_max:9/2016`

You can use this [list of all the updates](http://pokemongo.wikia.com/wiki/List_of_game_updates) to search for a specific release version and supply a date range that targets the time of that release. I may come back to this post to create a better timeline of the version changes for you.

**Comment by celandro** [comment]
Id suggest looking here, but it isnt very clean as the files were edited a bit

https://github.com/celandro/pokebattler-fight/commits/master/src/main/resources/com/pokebattler/fight/data/pokemongo.json
