### ISSUE TITLE
Add pokedex numbers

### ISSUE THREAD

**Issue by henrykuijpers** [BrunnerLivio/pokemongo-game-master#36]
It would be nice to also include the pokedex numbers. I.e. Bulbasaur 1, Ivysaur 2, etc.

**Comment by BrunnerLivio** [comment]
This is not part of this repository. This repository does not alter any data from the GAME_MASTER.protobuf files. What you're looking for is maybe the [pokemongo-json-pokedex](https://github.com/BrunnerLivio/pokemongo-json-pokedex) repository. 

You can parse it yourself from the `itemTemplates[x].templateId` => e.g. `V0001_POKEMON_BULBASAUR`
