### ISSUE TITLE
Updated dodge and camera distances

### ISSUE THREAD

**Issue by rmkane** [BrunnerLivio/pokemongo-game-master#39]
The following values in the `pokemonSettings.encounter` properties changed for a few Pokémon a couple days ago.

> [Original post](https://reddit.com/r/TheSilphRoad/comments/8432ci)

| Dex | Name | Template ID | Key | Old Value | New Value | 
|:-|:-|:-|:-|:-|:-|
| 015 | Beedrill | V0015_POKEMON_BEEDRILL | dodgeDistance | 0.25 | 0.125 | 
| 041 | Zubat | V0041_POKEMON_ZUBAT | dodgeDistance | 0.25 | 0.125 | 
| 081 | Magnemite | V0081_POKEMON_MAGNEMITE | dodgeDistance | 0.20000000298023224 | 0.10000000149011612 | 
| 082 | Magneton | V0082_POKEMON_MAGNETON | dodgeDistance | 0.20000000298023224 | 0.10000000149011612 | 
| 145 | Zapdos | V0145_POKEMON_ZAPDOS | dodgeDistance | 0.25 | 0.125 | 
| 165 | Ledyba | V0165_POKEMON_LEDYBA | dodgeDistance | 0.25 | 0.125 | 
| 166 | Ledian | V0166_POKEMON_LEDIAN | dodgeDistance | 0.20000000298023224 | 0.10000000149011612 | 
| 193 | Yanma | V0193_POKEMON_YANMA | dodgeDistance | 0.25 | 0.125 | 
| 284 | Masquerain | V0284_POKEMON_MASQUERAIN | dodgeDistance | 0.800000011920929 | 0.4000000059604645 | 
| 291 | Ninjask | V0291_POKEMON_NINJASK | dodgeDistance | 0.699999988079071 | 0.3499999940395355 | 
| 297 | Hariyama | V0297_POKEMON_HARIYAMA | cameraDistance | 7.0 | 6.0 | 
| 320 | Wailmer | V0320_POKEMON_WAILMER | cameraDistance | 5.0 | 4.5 | 
| 329 | Vibrava | V0329_POKEMON_VIBRAVA | dodgeDistance | 0.4000000059604645 | 0.20000000298023224 | 
| 357 | Tropius | V0357_POKEMON_TROPIUS | cameraDistance | 6.0 | 5.0 | 
| 383 | Groudon | V0383_POKEMON_GROUDON | cameraDistance | 7.0 | 6.0 | 
| 384 | Rayquaza | V0384_POKEMON_RAYQUAZA | cameraDistance | 6.0 | 5.0 |

**Comment by celandro** [comment]
Should be in https://github.com/BrunnerLivio/pokemongo-game-master/pull/40
