### ISSUE TITLE
Double cinematicMoves in Mew

### ISSUE THREAD

**Issue by Hedva** [BrunnerLivio/pokemongo-game-master#45]
Not sure it is a bug or as it is just provided by the game itself. But the following charged / cinematic moves are double in Mew

- Psychic (100)
- Ancient Power (70)
- Dragon Claw (50)
- Psyshock (65)
- Ice Beam (90)
- Blizzard (130)
- Hyper Beam (150)
- Solar Beam (180)
- Thunderbolt (80)
- Thunder (100)

**Comment by celandro** [comment]
Provided by the game itself. I had to dedupe in my own code.
