### ISSUE TITLE
0.59.1

### ISSUE THREAD

**Issue by BrunnerLivio** [BrunnerLivio/pokemongo-game-master#5]
Update files to 0.59.1

**Comment by hacknug** [comment]
I'm on it.

**Comment by celandro** [comment]
There was no Gamemaster change supposedly but probably new protos for the
java project

**Comment by hacknug** [comment]
I just extracted the GAME_MASTER and encountered this issue when trying to build the JSON version (this is actually a translation from the message in Spanish I got):  
`Error: Main class could not be found or loaded com.pokebattler.gamemaster.GenerateJSON`

**Comment by BrunnerLivio** [comment]
@celandro is right. We'll wait then until the [PR#278](https://github.com/AeonLucid/POGOProtos/pull/278) is merged

**Comment by AeonLucid** [comment]
@BrunnerLivio Merged.
