### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by BrunnerLivio** [BrunnerLivio/pokemongo-game-master#8]
I'm not a Java expert, but is it possible to create a Docker image with all its needed dependencies?
So a user, which does not know Java can simply build the container and generate a new JSON.

This would be really useful for lazy people like me, who don't want to install all the dependencies, just to generate the json file

**Comment by proegssilb** [comment]
Something like [this gist](https://gist.github.com/proegssilb/b5235474a5a33562129339bc34fe2b5d) should work, but it could be that PR #9 means version "latest" won't work for me until pogoprotos ([this repo?](https://github.com/AeonLucid/POGOProtos)) is updated. All I know is I've got maven running just fine, but there's a Protocol Buffers exception.

**Comment by celandro** [comment]
Please check my pull request. There was a compatibility  breaking change in
the pokémon go api. This should not happen with protobufs if managed
properly. Either the POGOProtos repo has an error or niantic screwed up.
Regardless the 2.7.0 version will read old protobufs and 2.8.0 will read
the new ones.

**Comment by BrunnerLivio** [comment]
@proegssilb 
Yes the dockerfile looks good!
Can you create a pull request with that gist, as soon as the issue is resolved?
